### ISSUE TITLE
Adding monogoDB schema

### ISSUE THREAD

**Issue by piyush-json** [shraddhapandeyy/college-api#16]
there are no data models for both faculty and libraries

**Comment by shraddhapandeyy** [comment]
Okay, If you are interested in creating that part, then i can assign you

**Comment by piyush-json** [comment]
yeah please assign me this

**Comment by shraddhapandeyy** [comment]
Okay assigned!

**Comment by piyush-json** [comment]
Also what are the data that are required to be stored?

for now
### Faculty
* name
* username
*  photo(url string)
*  subject(array)

not sure what data is to be stored related to **library**

**Comment by piyush-json** [comment]
@shraddhapandeyy  please help me with this.

**Comment by shraddhapandeyy** [comment]
You can choose the data to be stored according to your choice

**Comment by piyush-json** [comment]
Merged
