### ISSUE TITLE
create routes for students

### ISSUE THREAD

**Issue by shraddhapandeyy** [shraddhapandeyy/college-api#2]
folder structure should be
```
-src
   -routes
   -controllers
   -models
-index.js
-package.json
```
and use mysql for database if you want to add database as well

**Comment by Petsamuel** [comment]
What does the student Api entails ?

**Comment by SanjivKannaa** [comment]
could you please give a brief explaination on what is project is meant to do. I would like to work on the backend part but am not able to understand enough about the project.

**Comment by shraddhapandeyy** [comment]
Basically I want to create an API for college website, as you know, In the website there can be many sections like crud operations for students, faculties, library, etc..
So I want to create an API for that. I have not decided exactly what should api look like, but you can research and visit some other college websites and then implement whatever the part you like :)

**Comment by Anmol-Prasad** [comment]
Ok So I am interested to contribute to your project. I have previously worked a lot with NodeJs and MongoDB in similar projects. Would like to know more on exactly what kind of APIs you are expecting and will MongoDB work for the database?

**Comment by aritroCoder** [comment]
I know full stack web development along with RESTful API building, I think I can make a simple API for this project where we can store and fetch student data from MongoDB

**Comment by abhi887449** [comment]
please assign this task to me, I can create this API using node js and MySQL 
folder structure
```
-src
   -routes
     -student
     -classes
     -teacher
     -library
     -admin(all permission)
     -examination
     -admission
   -controllers
   -models
     -student
     -teachers
     -admin
     -subject
     -classes
     -newBookInLibrary
     -issueBook
-index.js
-package.json
```
please correct me if I forgot any route or model and also if I have made any mistake in the folder structure

**Comment by shraddhapandeyy** [comment]
@Anmol-Prasad @aritroCoder @abhi887449 
Hey Guys
Thank you for showing interest in this project
If you really want to work on this then you can create other issues as well and then ask me to assign you
@abhi887449 I see the directory structure you created its awesome, but if you will do all work then other contributors will have nothing to do in it, but i request you to create those files only (only create that directory structure) and work on any specific route, for now i am assigning you to this.

**Comment by abhi887449** [comment]
> @Anmol-Prasad @aritroCoder @abhi887449 Hey Guys Thank you for showing interest in this project If you really want to work on this then you can create other issues as well and then ask me to assign you @abhi887449 I see the directory structure you created its awesome, but if you will do all work then other contributors will have nothing to do in it, but i request you to create those files only (only create that directory structure) and work on any specific route, for now i am assigning you to this.

ok, I will update the directory structure soon and I will work on the student route
